# Site wide configuration

title: Tradução e Revisão
description: "Serviços de tradução e revisão textual"
logo: 120x120.gif
teaser: 400x250.gif
locale: pt-BR
#url: http://camyle.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Camyle de Araújo Silva
  web: http://camyle.github.io
  email: camyletrad@gmail.com
  twitter:
  bio: "Graduada em Tradução pela Univesidade Federal da Paraíba"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus:
    ad-client:
    ad-slot:
  disqus-shortname: camyle


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
